title: Rhys Gould


# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#  Description
# baseurl: ""
# url: https://r-gould.github.io
# twitter_username: jekyllrb
github_username: r-gould
linkedin_username: rhys-gould-a54361221

# remote_theme: pages-themes/slate@v0.2.0
# plugins:
# - jekyll-remote-theme

markdown: kramdown

minima:
  skin: classic
  
theme: minima
plugins:
  - jekyll-feed
